name: "Build"

on: [push, pull_request]

jobs:
  Matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Matrix
        id: matrix
        uses: Invicton-Labs/terraform-module-testing-configuration/matrix@dev
        with:
          minimum_tf_version: '0.13.0'

      - name: Output Matrix
        run: |
          echo "TF Versions: ${{ steps.matrix.outputs.terraform_versions }}"
          echo "Images: ${{ steps.matrix.outputs.images }}"
          echo "Windows Versions: ${{ steps.matrix.outputs.windows_versions }}"
          echo "Mac Versions: ${{ steps.matrix.outputs.mac_versions }}"
