name: "Build"

on: [push, pull_request]

jobs:
  Matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Matrix
        id: matrix
        uses: Invicton-Labs/terraform-module-testing-configuration/matrix@dev
        with:
          minimum_tf_version: '0.13.0'

      - name: Output Matrix
        run: |
          echo "Strategy: ${{ steps.matrix.outputs.strategy }}"

    outputs:
      strategy: ${{ steps.matrix.outputs.strategy }}
          
  Test:
    needs: [Matrix]
    strategy: ${{ fromJSON(needs.Matrix.outputs.strategy)}}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ fromJSON(matrix.container) }}
    steps:
      - name: Run Tests
        id: tests
        uses: Invicton-Labs/terraform-module-testing-configuration/test@dev
        with:
          testing_path: tester
